FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY RabbitMqDemo.csproj ./

RUN dotnet restore

COPY . .

RUN dotnet publish RabbitMqDemo.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:8.0 

WORKDIR /app

COPY --from=build /app/out .

ENTRYPOINT ["dotnet","RabbitMqDemo.dll"]

